- name: Playbook for adding objects and rules to Dynamic Layer
  connection: httpapi
  hosts: GW1
  gather_facts: false
  collections:
  - check_point.gaia
  vars:
    state: present
  tasks:
    - name: Fill Dynamic Layer with objects and rules
      cp_gaia_dynamic_content:
        policy_path: "./GW1-Dynamic-Layer.json"
        dry_run: false
        tags: ["JIRA-12345", "add rules to gw1 dynamic layer"]
        comments: "Updating Dynamic Layer"
        wait_for_task: true